apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  labels:
    app: fastapi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
        - name: fastapi-backend
          image: moenesbens/fastapi-back
          env:
            - name: DOMAIN
              value: 'fastapi-backend' # Changd this
            - name: ENVIRONMENT
              value: 'local'
            - name: BACKEND_CORS_ORIGINS
              value: 'http://localhost,http://localhost:5173,https://localhost,https://localhost:5173,http://localhost.tiangolo.com'
            - name: SECRET_KEY
              value: 'changethis'
            - name: FIRST_SUPERUSER
              value: 'admin@example.com'
            - name: FIRST_SUPERUSER_PASSWORD
              value: 'changethis'
            - name: USERS_OPEN_REGISTRATION
              value: 'False'
            - name: SMTP_HOST
              value: ''
            - name: SMTP_USER
              value: ''
            - name: SMTP_PASSWORD
              value: ''
            - name: EMAILS_FROM_EMAIL
              value: 'info@example.com'
            - name: SMTP_TLS
              value: 'True'
            - name: SMTP_PORT
              value: '587'
            - name: SMTP_SSL
              value: 'False'
            - name: POSTGRES_SERVER
              value: 'postgres'
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: 'app'
            - name: POSTGRES_USER
              value: 'postgres'
            - name: POSTGRES_PASSWORD
              value: 'changethis'
            - name: SENTRY_DSN
              value: ''
            - name: PROJECT_NAME
              value: 'Fast api usermanager'
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend-service
spec:
  selector:
    app: fastapi-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
